version: '3.9'
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec pumactl start"
    volumes:
      - .:/myapp
      - tmp-data:/myapp/tmp
    environment:
      - RAILS_ENV=production
      - WEB_CONCURRENCY=1
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "3080:80"
    volumes:
      - .docker/nginx/conf.d:/etc/nginx/conf.d
      - tmp-data:/myapp/tmp
    depends_on:
      - app
volumes:
  tmp-data: